modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CoolAid48/Disenchant-Curses/issues"
license = "MIT"

[[mods]]
modId = "disenchant_curses"
version = "0.3.0"
displayName = "Disenchant Curses"
authors = "CoolAid48"
credits = "Mod icon by MandaLin"
description = '''
Remove curses from books and gear with a grindstone as you would with any other enchant
'''
logoFile = "assets/disenchant-curses/icon.png"

[[mixins]]
config = "disenchant-curses.mixins.json"
